// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rcbhpyhtaefbywohbhkv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjYmhweWh0YWVmYnl3b2hiaGt2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwOTM2OTAsImV4cCI6MjA2NTY2OTY5MH0.a6M_1VQCulDqz8Zvrl92QcD4KilhNp8WkRvgIj_sEKA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);